#!/usr/bin/python3
axlsql = open("import.xml","w")

axlsql.write("""<?xml version="1.0" encoding="UTF-8"?>
<!--DTD generated by XMLSPY v5 rel. 4 U (http://www.xmlspy.com)-->
<!DOCTYPE data [
	<!ELEMENT data (sql+)>
	<!ELEMENT sql EMPTY>
	<!ATTLIST sql
	query CDATA #IMPLIED
		update CDATA #IMPLIED
>
]>
<data>""")  #####Cisco Black Magic Header

axlsql.write("</data>") ####Cisco Black Magic Footer