#!/usr/bin/python3
import csv
import glob
import sqlite3
axlsql = open("import.xml","w")

def personaladdressbook(enduser, firstname, lastname, nickname, email):
  query='INSERT into personaladdressbook (fkenduser, firstname, lastname, nickname, email) VALUES ((select pkid from enduser where userid = "'+enduser+'"),"'+firstname+'","'+lastname+'","'+nickname+'","'+email+'")'
  row='<sql query="'+query+'"/>\n'
  axlsql.write(row)

def personalphonebook(enduser, nickname, tkpersonalphonenumber, phonenumber):
  query='INSERT into personalphonebook (fkenduser, fkpersonaladdressbook, tkpersonalphonenumber, phonenumber) VALUES ((select pkid from enduser where userid = "'+enduser+'"),(SELECT pkid FROM personaladdressbook WHERE nickname = "'+nickname+'" AND fkenduser = (select pkid from enduser where userid = "'+enduser+'")),"'+tkpersonalphonenumber+'","'+phonenumber+'")'
  row='<sql query="'+query+'"/>\n'
  axlsql.write(row)

def speeddial(device, speeddialindex, speeddialnumber, label, labelascii):
  query='INSERT INTO speeddial (fkdevice, speeddialindex, speeddialnumber, label, labelascii) VALUES ((SELECT pid FROM device WHERE name = "'+device+'"),"'+speeddialindex+'","'+speeddialnumber+'","'+label+'","'+labelascii+'")'
  row='<sql query="'+query+'"/>\n'
  axlsql.write(row)

axlsql.write("""<?xml version="1.0" encoding="UTF-8"?>
<!--DTD generated by XMLSPY v5 rel. 4 U (http://www.xmlspy.com)-->
<!DOCTYPE data [
  <!ELEMENT data (sql+)>
  <!ELEMENT sql EMPTY>
  <!ATTLIST sql
    query CDATA #IMPLIED
    update CDATA #IMPLIED
>
]>
<data>""")  #####Cisco Black Magic Header

conn = sqlite3.connect(':memory:')
c = conn.cursor()
c.execute('CREATE TABLE contact (firstname TEXT, lastname TEXT, nickname TEXT, phonenumber TEXT, tkpersonalphonenumber TEXT, email TEXT, userid TEXT)')
conn.commit()

contacts = glob.glob("./output/contacts/in/*.csv")

for file in contacts:   #Import speeddials into database
  userid=file.split("/")[-1].split(".csv")[0]  #get userid, strip path and csv from filename
  contact=open(file,"r")
  dialect = csv.Sniffer().sniff(contact.read(1024))
  contact.seek(0)
  reader= csv.reader(contact, dialect)
  for i in reader:
  	i.append(userid)
  	c.execute('INSERT INTO contact values (?,?,?,?,?,?,?)',i)

conn.commit()

c.execute('SELECT userid FROM contact GROUP BY userid')
users = c.fetchall()

for i in users:
  c.execute('SELECT firstname, lastname, nickname, email FROM contact WHERE userid = (?) GROUP BY nickname',(i[0],))
  oneuserscontacts=c.fetchall()
  for entry in oneuserscontacts:
    personaladdressbook(i[0], entry[0], entry[1], entry[2], entry[3])
    c.execute('SELECT tkpersonalphonenumber, phonenumber from contact WHERE userid = (?) AND nickname = (?)',(i[0],entry[1]))
    onecontactsnumbers = c.fetchall()
    for number in onecontactsnumbers:
      personalphonebook(i[0], entry[2], number[0], number[1])


speeddials = glob.glob("./output/speeddial/in/*.csv")

for file in speeddials:   #Import speeddials into database
  devicename=file.split("/")[-1].split(".csv")[0]  #get devicename, strip path and csv from filename
  device=open(file,"r")
  dialect = csv.Sniffer().sniff(device.read(1024))
  device.seek(0)
  reader= csv.reader(device, dialect)
  for i in reader:
  	speeddial(devicename, reader[0], reader[1], reader[2], reader[3])
  	


axlsql.write("</data>") ####Cisco Black Magic Footer
